# Generated by Django 5.2.1 on 2025-05-13 17:07

from django.db import migrations


def create_test_users(apps, schema_editor):
    User = apps.get_model('users', 'User')
    User.objects.bulk_create([User(
        email=f'testmail{i}@example.com',
        phone_number=f'+123456789{i}',
        first_name=f'FirstName{i}',
        last_name=f'LastName{i}',
        middle_name=f'MiddleName{i}',
    ) for i in range(100)])

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_test_users)
    ]
