# Generated by Django 5.2.1 on 2025-05-14 00:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingcustomer',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_customers', to=settings.AUTH_USER_MODEL, verbose_name='Customer'),
        ),
        migrations.AddField(
            model_name='booking',
            name='customers',
            field=models.ManyToManyField(related_name='bookings', through='hotel.BookingCustomer', to=settings.AUTH_USER_MODEL, verbose_name='Customers'),
        ),
        migrations.AddField(
            model_name='bookingpayment',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='hotel.booking', verbose_name='Booking'),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='booking_customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_codes', to='hotel.bookingcustomer', verbose_name='Booking customer'),
        ),
        migrations.AddField(
            model_name='review',
            name='booking_customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='hotel.bookingcustomer', verbose_name='Booking customer'),
        ),
        migrations.AddField(
            model_name='room',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hotel.category', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='hotel.room', verbose_name='Room'),
        ),
        migrations.AddField(
            model_name='roomamenity',
            name='amenity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_amenities', to='hotel.amenity', verbose_name='Amenity'),
        ),
        migrations.AddField(
            model_name='roomamenity',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_amenities', to='hotel.room', verbose_name='Room'),
        ),
        migrations.AddField(
            model_name='room',
            name='amenities',
            field=models.ManyToManyField(related_name='rooms', through='hotel.RoomAmenity', to='hotel.amenity', verbose_name='Amenities'),
        ),
        migrations.AddField(
            model_name='roomimage',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='hotel.room', verbose_name='Room'),
        ),
        migrations.AddConstraint(
            model_name='bookingcustomer',
            constraint=models.UniqueConstraint(fields=('customer', 'booking'), name='unique_booking_customer'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('check_in__lt', models.F('check_out'))), name='check_in_before_check_out'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('room', 'check_in', 'check_out'), name='unique_booking_room_dates'),
        ),
        migrations.AddConstraint(
            model_name='roomamenity',
            constraint=models.UniqueConstraint(fields=('amenity', 'room'), name='unique_room_amenity'),
        ),
    ]
