# Generated by Django 5.2.1 on 2025-05-14 08:30

from django.db import migrations
import random


def create_test_categories(apps, schema_editor):
    Category = apps.get_model('hotel', 'Category')
    categories = [
        {'name': 'Standard', 'description': 'Basic comfortable room'},
        {'name': 'Deluxe', 'description': 'Spacious room with additional amenities'},
        {'name': 'Suite', 'description': 'Large premium room with separate living area'},
        {'name': 'Family', 'description': 'Spacious room suitable for families with children'},
        {'name': 'Executive', 'description': 'Premium room with business facilities'},
    ]
    Category.objects.bulk_create([Category(**category) for category in categories])


def create_test_amenities(apps, schema_editor):
    Amenity = apps.get_model('hotel', 'Amenity')
    amenities = [
        {'name': 'Wi-Fi', 'description': 'High-speed wireless internet'},
        {'name': 'Air Conditioning', 'description': 'Climate control system'},
        {'name': 'TV', 'description': '42-inch flat-screen TV'},
        {'name': 'Mini Bar', 'description': 'Stocked refrigerator with beverages'},
        {'name': 'Coffee Machine', 'description': 'Premium coffee maker'},
        {'name': 'Safe', 'description': 'In-room electronic safe'},
        {'name': 'Bathtub', 'description': 'Luxury bathtub'},
        {'name': 'Balcony', 'description': 'Private balcony with view'},
    ]
    Amenity.objects.bulk_create([Amenity(**amenity) for amenity in amenities])



class Migration(migrations.Migration):
    dependencies = [
        ('hotel', '0002_initial'),
    ]

    operations = [
        migrations.RunPython(create_test_categories),
        migrations.RunPython(create_test_amenities),
    ]